[project]
name = "earthengine-dask"
version = "0.1.0"
description = "Add a short description here"
authors = ["Tyler Erickson <tyler@vorgeo.com>"]
channels = ["conda-forge"]
platforms = ["osx-arm64"]

[tasks]
jlab = "jupyter lab --ContentsManager.allow_hidden=True"

[dependencies]
python = "3.11.*"
nbdev = ">=2.2.10,<2.3"
coiled = ">=1.24.0,<1.25"
jupyter = ">=1.0.0,<1.1"
earthengine-api = ">=0.1.404,<0.2"
altair = ">=5.3.0,<5.4"
pandas = ">=2.2.2,<2.3"
quarto = ">=1.4.550,<1.5"
