[project]
name = "earthengine-dask"
version = "0.1.0"
description = "Add a short description here"
authors = ["Tyler Erickson <tyler@vorgeo.com>"]
channels = ["conda-forge"]
platforms = ["osx-arm64"]

[tasks]

[dependencies]
python = "3.11.*"
nbdev = ">=2.2.10,<2.3"
