# Autogenerated by nbdev

d = { 'settings': { 'branch': 'master',
                'doc_baseurl': '/earthengine-dask',
                'doc_host': 'https://VorGeo.github.io',
                'git_url': 'https://github.com/VorGeo/earthengine-dask',
                'lib_path': 'earthengine_dask'},
  'syms': {'earthengine_dask.core': {'earthengine_dask.core.foo': ('core.html#foo', 'earthengine_dask/core.py')}}}