# AUTOGENERATED! DO NOT EDIT! File to edit: ../00_core.ipynb.

# %% auto 0
__all__ = ['InitEarthEngine', 'ClusterGEE', 'ClientGEE']

# %% ../00_core.ipynb 3
import logging

import coiled
import dask.distributed
import ee

# %% ../00_core.ipynb 6
class InitEarthEngine(dask.distributed.WorkerPlugin):
    def __init__(self, **kwargs):
        logging.warning('InitEarthEngine init')  # This appears in the notebook output where the cluster is initiated.
        self.kwargs = kwargs

    def setup(self, worker):
        logging.warning('InitEarthEngine setup')  # This appears in the dask cluster logs.
        logging.info('test info')
        logging.debug('test debug')
        logging.error('test error')
        import ee
        ee.Initialize(**self.kwargs)


class ClusterGEE(coiled.Cluster):
    def __init__(self, **kwargs):
        logging.info('ClusterGEE init')
        logging.warning('ClusterGEE init')
        super().__init__(**kwargs)
        self.wait_for_workers(kwargs['n_workers'])
        coiled.credentials.google.send_application_default_credentials(self)

    def get_client(self):
        logging.info('ClusterGEE get_client')
        logging.warning('ClusterGEE get_client')
        client = super().get_client()
        client.register_plugin(InitEarthEngine())
        return client


class ClientGEE(dask.distributed.client.Client):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
